### ISSUE TITLE
Nexus Modpage

### ISSUE THREAD

**Issue by Archer7x** [tienducle/Stardew-Valley-Expanded-DE-Translation#10]
Hey,
vielen dank für die credits und das Vertrauen! :D

Ich würde gerne wissen warum auf der NexusMods Seite die Vortex Optionen deaktiviert sind?
Die Checkboxen für:
-Remove the 'Download with manager' button
-Set the file as the main Vortex file
Und dann natürlich auch: [Main Vortex file] unter Files auswählen.
Das einzuschalten macht es viel angenehmer die Mod zu installieren.

Ich würde außerdem sehr empfehlen die Zip-Datei der Mod umzubenennen von "Stardew Valley Expanded - Zip"
in z.B. "Stardew Valley Expanded - German". Ebenso die Übersetzungen für die Maps wie z.B. die "Frontier Farm".
Wenn die Übersetzung installiert ist, hat sie in Vortex den selben Namen wie die eigentliche Mod was zu Verwirrung führt.
Außerdem ist mindestens in der "Frontier Farm" auch die default.json Datei enthalten. Dadurch weiß Vortex nicht welche
Datei es verwenden soll. Ich würde diese aus der Übersetzung entfernen und empfehlen alle Übersetzungsmods
in z.B. "Frontier Farm - German" umbenennen.

Außerdem habe ich meinen username auf Github und NexusMods zu  @Archer7x geändert.
Ich würde mich freuen, wenn du das überall updaten könntest. :D

Dies sind natürlich nur Vorschläge. 
Und vielen Dank für die Arbeit die ihr bereits in die Übersetzung hineingesteckt habt!

Viele Grüße!
Archer

**Comment by tienducle** [comment]
Hi,

ich hatte die ganzen Optionen für die Mod Manager ausgeschalten, weil die Installation nie geklappt hat. Leider hatte ich auch noch keine Zeit, mich mit den Tools näher zu beschäftigen, aber das ergibt jetzt Sinn, was du erklärt hast! :D

Ich passe die nächsten Tage mal das Skript an, das die Zip Dateien für Nexusmods erstellt, sodass die default.json Dateien nicht mehr inkludiert werden und ändere noch die Dateinamen. Und dann würde ich beim nächsten Upload die Vortex Optionen wieder einschalten.

Danke dir für die Tipps & Vorschläge! :)

**Comment by tienducle** [comment]
Nachtrag: Hmmm.. wenn die Änderungen an den Dateien das Problem mit Vortex beheben, dann lasse ich auch den "Installer" in Zukunft weg.
