### ISSUE TITLE
Braking Bug!

### ISSUE THREAD

**Issue by Archer7x** [tienducle/Stardew-Valley-Expanded-DE-Translation#15]
Hi, 
die Mod-Ordnerstruktur muss unbedingt geändert werden!
Einen Ordner mit dem Namen der eigenen Übersetzungsmod,
und einen Ordner mit dem original Namen und Struktur der zu übersetzenden Mod.
Dies gilt auch für die Frontier Farm und alle anderen Mods!
Die Struktur muss nach dem entpacken der Zip wie folgt sein:

Stardew Valley Expanded - German.zip/
├─ Stardew Valley Expanded - German/
│  ├─ manifest.json
├─ Stardew Valley Expanded/
│  ├─ i18n/
│  │  ├─ de.json

![grafik](https://github.com/user-attachments/assets/d06c29bd-93c3-4249-9cd4-eff8fa589a50)

**Comment by tienducle** [comment]
`Man sieht dann nur nicht, dass es ein Update von der Übersetzung gibt.`

Also zumindest nicht im SMAPI Log, aber dadurch, dass man die Dateien über Vortex installiert hat, sieht man es auch dort, wenn es ein Update gibt.

**Comment by Archer7x** [comment]
Komisch. Ich glaube ich hatte das mal hingekriegt aber vielleicht liege ich da auch falsch. Eigentlich braucht man den Ordner mit der Manifest.jason damit Worte weiß, welche Version die Übersetzung hat und ob sie installiert ist. Ich schau mir das noch mal genauer an und teste das.
